# Generated by Django 4.2.7 on 2023-11-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='product_photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
