# Generated by Django 4.2.7 on 2023-12-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_tbl_product_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order',
            name='status',
            field=models.CharField(default='pending', max_length=100),
            preserve_default=False,
        ),
    ]
