# Generated by Django 5.0 on 2023-12-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_tbl_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order',
            name='User_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
