# Generated by Django 5.0 on 2023-12-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_tbl_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_order',
            name='User_id',
            field=models.CharField(max_length=100),
        ),
    ]
