# Generated by Django 5.0 on 2023-12-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_alter_tbl_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='address',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
