# Generated by Django 5.0 on 2023-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_tbl_payment_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_payment',
            name='address',
        ),
        migrations.AddField(
            model_name='tbl_payment',
            name='User_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
